# Generated by Django 4.2.2 on 2024-01-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "stage_name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("social_link", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["stage_name"],
            },
        ),
    ]
