# Generated by Django 4.2.2 on 2023-12-30 03:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("artists", "0001_initial"),
        ("albums", "0003_alter_album_creation_datetime_alter_album_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="album",
            unique_together={("artist", "name")},
        ),
    ]
