# Generated by Django 4.2.2 on 2023-12-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("albums", "0004_alter_album_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="name",
            field=models.CharField(max_length=20),
        ),
    ]
